vich_uploader:
    db_driver: orm

    mappings:
       oiseau_image:
           uri_prefix: /images/oiseaux
           upload_destination: '%kernel.project_dir%/public/images/oiseaux'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
